### ISSUE TITLE
Add package to nixpkgs

### ISSUE THREAD

**Issue by Stunkymonkey** [SuperSandro2000/nixpkgs-review-checks#4]
currently the installation is not ideally. (adding specific packages to the system and then sourcing the `bashrc`.)

I would prefer to have a package, that contains a bash script called: `nixpkgs-review-checks` which does the same as sourcing the `bashrc` and running `nixpkgs-review`.

**Comment by SuperSandro2000** [comment]
I am currently working on the required changes to make everything work with ``nixpkgs-review-checks`` and a default.nix. If that is finished I think about adding it to nixpkgs.

**Comment by SuperSandro2000** [comment]
https://github.com/jtojnar/nixpkgs-hammering is not in nixpkgs currently and I am hard depending on it but I think I can create a flake instead.

**Comment by Stunkymonkey** [comment]
Any news here?

**Comment by SuperSandro2000** [comment]
The tool is still very experimental and not ready to use for the broad public. I am not planning to upstream it.
